version: '3.5'
services:
  #--------------------- prometheus -------------------------
  prometheus:
    image:          prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
    ports:
      - 127.0.0.1:9090:9090
    networks:
      - monitoring-net
    restart: always

  #--------------------- node-exporter -------------------------
  node-exporter:
    image:          prom/node-exporter
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    hostname: monitoring
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - 127.0.0.1:9100:9100
    networks:
      - monitoring-net
    restart: always

  #--------------------- blackbox-exporter -------------------------
  blackbox-exporter:
    image:          prom/blackbox-exporter
    container_name: blackbox-exporter
    volumes:
      - ./blackbox:/etc/blackbox_exporter/
    ports:
      - 127.0.0.1:9115:9115
    networks:
      - monitoring-net
    restart: always

  #--------------------- grafana -------------------------
  grafana:
    image:          grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - monitoring-net
    volumes:
      - type:      volume
        source:    grafana-provisioning-vol
        target:    /etc/grafana/provisioning/
        read_only: false
      - type:      volume
        source:    grafana-data-vol
        target:    /var/lib/grafana
        read_only: false
    restart: always

  #--------------------- alertmanager -------------------------
  alertmanager:
    image: prom/alertmanager:v0.21.0
    container_name: alertmanager
    ports:
      - 127.0.0.1:9093:9093
    networks:
      - monitoring-net
    restart: always

volumes:
  grafana-provisioning-vol:
    name:   grafana-provisioning-vol
    driver: local
  grafana-data-vol:
    name:   grafana-data-vol
    driver: local
        
networks:
  monitoring-net:
    name:   monitoring-net
    driver: bridge
