groups: 
- name:    example
  rules:
  - alert: PrometheusTargetMissing
    expr:  up == 0
    for:   0m
    labels:
      severity:    critical
    annotations:
      summary:     "Prometheus target missing (instance {{ $labels.instance }})"
      description: "A Prometheus target has disappeared. An exporter might be crashed. VALUE = {{ $value }}  LABELS: {{ $labels }}"

  - alert: HttpCodeError
    expr:  probe_http_status_code != 200
    for:   0m
    labels:
      severity:    critical
    annotations:
      summary:     "Http status code is not 200 (instance {{ $labels.instance }})"
      description: "Http status code is not 200 (instance {{ $labels.instance }})"

  - alert: HttpDelayError
    expr: probe_http_duration_seconds > 5.0
    for: 0m
    labels:
      severity:    critical
    annotations:
      summary:     "Http delay is too large (instance {{ $labels.instance }})"
      description: "Http delay is too large (instance {{ $labels.instance }})"

  - alert: HttpUnreach
    expr: probe_success != 1
    for: 0m
    labels:
      severity:    critical
    annotations:
      summary:     "Http unreachable (instance {{ $labels.instance }})"
      description: "Http unreachable (instance {{ $labels.instance }})"
