scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: blackbox
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [http_probe]  # Look for a HTTP 200 response.
    static_configs:
    - targets:
      - https://lms.skillfactory.ru    # Target to probe with http.
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-exporter:9115

rule_files:
  - 'alert-rules.yml'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"