modules:
  http_probe:
    prober:  http
    timeout: 5s
    http:
      method:              GET
      no_follow_redirects: false
      fail_if_ssl:         false
      fail_if_not_ssl:     false
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback:   false
